FROM ipfs/go-ipfs:v0.4.17

# This is a customized insecure config to open wide to the world
COPY ./ipfs-bin-container_daemon.sh /usr/local/bin/start_ipfs

# This just makes sure that:
# 1. There's an fs-repo, and initializes one if there isn't.
# 2. The API and Gateway are accessible from outside the container.
ENTRYPOINT ["/sbin/tini", "--", "/usr/local/bin/start_ipfs"]

# Execute the daemon subcommand by default
CMD ["daemon", "--migrate=true"]
